#:kivy 1.10.0

FloatLayout:
    Bubble:
        arrow_pos: "bottom_mid"
        size_hint: (0.3, 0.3)
        pos_hint: {'center_x': .5, 'y': .6}

        GridLayout:
            cols: 3
            BubbleButton:
                text: '7'
                on_release:
                    text_input.text += self.text
            BubbleButton:
                text: '8'
                on_release:
                    text_input.text += self.text
            BubbleButton:
                text: '9'
                on_release:
                    text_input.text += self.text
            BubbleButton:
                text: '4'
                on_release:
                    text_input.text += self.text
            BubbleButton:
                text: '5'
                on_release:
                    text_input.text += self.text
            BubbleButton:
                text: '6'
                on_release:
                    text_input.text += self.text
            BubbleButton:
                text: '1'
                on_release:
                    text_input.text += self.text
            BubbleButton:
                text: '2'
                on_release:
                    text_input.text += self.text
            BubbleButton:
                text: '3'
                on_release:
                    text_input.text += self.text
            BubbleButton:
                text: '0'
                on_release:
                    text_input.text += self.text
            BubbleButton:
                text: "Clear"
                on_release:
                    text_input.text = ""
            BubbleButton:
                text: "Send"

    TextInput:
        id: text_input
        pos_hint: {'center_x': .5, 'y': .54}
        size_hint: (0.2, 0.06)
        cursor_blink: True
        font_size: 20
        multiline: False
