<EVA_Pictures>:
    name: 'eva_pictures'
    FloatLayout:
        AsyncImage:
            id: EVAimage
            source: ""
            fit_mode: "contain"
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            opacity: 0.0
        Button:
            size_hint: 0.2,0.1
            pos_hint: {"Left": 1, "Bottom": 1}
            text: 'Return'
            font_size: 30
            on_release: app.root.current = 'us_eva'
