#!/usr/bin/env python3
"""
Generate 3-D print checklist table for ISS-Mimic.
Requires: python-github-api  (pip install PyGithub)
Usage:    python make_print_table.py > wiki/3d_print_checklist.md
"""

import os
from github import Github
from tabulate import tabulate   # pip install tabulate
import textwrap

REPO   = "ISS-Mimic/Mimic"
PATH   = "3D_Printing"
TOKEN  = ""          # Optional: set a GitHub PAT or leave blank for anonymous

g = Github(TOKEN) if TOKEN else Github()   # ← REPLACE the old line
tree = g.get_repo(REPO).get_git_tree("main", recursive=True).tree

parts = [n.path for n in tree
         if n.type == "blob"
         and n.path.startswith(PATH)
         and n.path.lower().endswith((".stl", ".3mf"))]

rows = [[f"- [ ] `{p.split('/')[-1]}`",   # unchecked box + file name
         "",                              # qty – fill in later
         "",                              # material
         p.replace(f"{PATH}/", "")]       # relative path for convenience
        for p in sorted(parts, key=str.lower)]

header = ["Print", "Qty", "Material", "Path in repo"]
md = tabulate(rows, headers=header, tablefmt="github")

front_matter = textwrap.dedent(f"""
    <!--
    Auto-generated by make_print_table.py
    Run the script after adding/removing STL/3MF files.
    -->
    # ISS Mimic – 3-D Printing Checklist
    Paste this table into the project wiki and tick things off as you go.
    """)

print(front_matter.strip(), "\n\n", md, sep="")
